name: Demo Workflow

on: 
  push:
    branches:
      - github-actions-demo

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - name: Starting Script
        run: echo "Hello World!"
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            # --- install packages ---
            sudo apt update -y && sudo apt install -y python3 python3-pip git

            # --- clone repo ---
            git clone https://github.com/professordiogodev/devops.flaskerino

            # Install Python Dependencies
            cd devops.flaskerino
            pip3 install -r requirements.txt

            # --- Create a systemd service ---
            echo "creating service..."

